export const Url = `${process.env.NEXT_PUBLIC_API}`+"/api/"
export const searchUserUrl = Url+"user/searchuser"
export const getUsersUrl = Url +"user" 
export const saveChatUrl = Url +"user/chat" 
export const getChatUrl = Url +"user/chat?chatId=" 
