export const Url = "https://chat-py9ch7t7l-mahenvs-projects.vercel.app/api/"
export const searchUserUrl = Url+"user/searchuser"
export const getUsersUrl = Url +"user" 
export const saveChatUrl = Url +"user/chat" 
export const getChatUrl = Url +"user/chat?chatId=" 
